# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25f98d442b98ababfe09963dfef41a0390a793c2edcac1efcaf2f9d1c4c139c5a875627ecc9d42f970ea052315d85a4a19cb8febf3df822c3fbb30f4d9af2fc3

test:
  secret_key_base: 684eabf9f012ecc73bfde0d5be5527648e08706ea55a0ca20e3fd764ad629df7091ee8c4c4c4b50d486cd691be45bddbf7ad7ce49449e1aa3e6fbc5213e306de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
